In [42]:
import numpy as np
import pandas as pd
import sqlite3

# create a new connection to a db in memory
conn = sqlite3.connect('data/van_crime_2003.db')

# create a cursor
c = conn.cursor()

# restore the given van_crime_2003.sql dump
c.executescript(open('data/van_crime_2003.sql', 'r').read())

van_crimes_df = pd.read_sql('SELECT * FROM van_crimes WHERE hour > 14', conn)

late_crimes = van_crimes_df.loc[van_crimes_df['HOUR'] > 18]

dangerous_month_crimes = van_crimes_df.loc[:, 'MONTH'].value_counts().head(1)

In [43]:
van_crimes_df

,TYPE,YEAR,MONTH,DAY,HOUR,MINUTE,HUNDRED_BLOCK,NEIGHBOURHOOD,X,Y
0,Theft from Vehicle,2003,11,17.0,16.0,0.0,56XX OAK ST,South Cambie,490682.32,5453536.96
1,Theft from Vehicle,2003,12,28.0,16.0,45.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36
2,Theft from Vehicle,2003,12,12.0,15.0,30.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36
3,Theft from Vehicle,2003,11,5.0,16.0,30.0,85XX STANLEY PARK DR,Stanley Park,489104.19,5460347.36
4,Theft of Vehicle,2003,9,2.0,21.0,0.0,20XX E 28TH AVE,Kensington-Cedar Cottage,495267.03,5454779.05
...,...,...,...,...,...,...,...,...,...,...
373,Break and Enter Residential/Other,2003,2,12.0,18.0,0.0,10XX HARWOOD ST,West End,490370.04,5458403.21
374,Theft of Vehicle,2003,12,17.0,17.0,0.0,1XX W KENT S AV,Marpole,492065.05,5450413.09
375,Break and Enter Residential/Other,2003,6,11.0,15.0,45.0,10XX HARWOOD ST,West End,490370.04,5458403.21
376,Theft of Vehicle,2003,4,1.0,21.0,0.0,6XX W 8TH AVE,Fairview,491445.25,5456826.01
377,Theft of Vehicle,2003,8,29.0,23.0,0.0,6XX W 8TH AVE,Fairview,491445.25,5456826.01

In [48]:
dangerous_month_crimes

6    51
Name: MONTH, dtype: int64


### TASK 2